### ISSUE TITLE
items[25] is undefined

### ISSUE THREAD

**Issue by SouDescolado** [gamehelp16/thegoldfactory#3]
You cannot mix 1 lava bucket 1 x potion and 1000 iron bars. :)

**Comment by gamehelp16** [comment]
Sorry I don't understand what you mean, could you please elaborate more on it?

**Comment by SouDescolado** [comment]
If you try to mix (In order) 1 lava bucket, 1 potion and 1000 iron bars it doesn't work. Its the recipe to make the item[25]. I guess you would have the same problem if you tried to craft shurikens, since its item[26]

**Comment by gamehelp16** [comment]
Are there any error messages on the dev console? Also could you please share your save code?

**Comment by SouDescolado** [comment]
TypeError: items[25] is undefined[Learn More] base.js:3024:1
	mixitems https://gamehelp16.github.io/thegoldfactory/base.js:3024:1
	onclick https://gamehelp16.github.io/thegoldfactory/:1:1

**Comment by SouDescolado** [comment]
NDYwNTg0NjN8NDYyMzk5OXwxMDAwMHwxMDAwMDB8MTAwMHwxfDEwMDAwMHwwfDV8MXw0MTIwfDF8MXwxfDB8MXwwfDI5N3wxMDF8M3w0fDk5fDF8MHwwfDI5OXwwfDB8MXwxfDB8MHwxMDIzfDB8MXwxMHw0fDh8NnwyfFlvdXxUaGlzIGlzIHlvdS58MHwwfDF8MHxmYWxzZXxmYWxzZXxmYWxzZXwwfGZhbHNlfHRydWV8dGh1bmRlcnw5OTl8NXwxfDF8ZmFsc2V8MHwwfDk5OTk5OTk5OXwyfEVtZXJhbGQgU3dvcmR8dHJ1ZXx0cnVlfHRydWV8dHJ1ZXx0cnVlfHRydWV8dHJ1ZXx0cnVlfHRydWV8ZmFsc2V8ZmFsc2V8dHJ1ZXw1fGZhbHNlfHRydWU=encrypted

**Comment by gamehelp16** [comment]
So if I remember correctly (this game is pretty old and quite frankly I don't really remember a lot of things about them anymore :d) these items were originally planned to be in the game but I decided to not add them into the game (because there are no other instances of item 25 and 26 in the code), sorry for the disappointing response.

**Comment by SouDescolado** [comment]
Oh well.. It happens then. Thank you.
